openapi: '3.1.0'
info:
  title: CompanionService
  version: 1.0.0
servers:
  - url: /api
paths:
  /devices:
    get:
      operationId: getDevices
      responses:
        '200':
          description: A list of available devices.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Devices'

components:
  schemas:
    Devices:
      type: object
      properties:
        devices:
          type: array
          items:
            type: string
      required:
        - devices
