name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - run: swift test
        env:
          DEVELOPER_DIR: /Applications/Xcode_15.0.1.app/Contents/Developer
